[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "gatoh"
version = "2026.08.0"
authors = [
    { name="Manuel Munizaga Sepulveda", email="manuel.chile@yahoo.com" },
]
description = "An open source agent-based modelling framework"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "polars",
    "rustworkx",
    "matplotlib",
    "scipy",
    "pyyaml",
    "multimethod",
    "seaborn",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/JungleHollow/GATOH"
Issues = "https://github.com/JungleHollow/GATOH/issues"

[project.optional-dependencies]
dev = [
    "bumpver",
    "sphinx",
    "scipy-stubs",
    "typing-extensions"
]

[tool.setuptools.packages]
find = {}

[tool.bumpver]
current_version = "2026.08.0"
version_pattern = "YYYY.0M.PATCH"
commit_message = "Bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true
push = true
allowed_branches = "master,main,default,release*"

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"',
]
"./docs/conf.py" = [
    'version = "{version}"',
    'release = "{version}"'
]
"./docs/index.rst" = [
    "**Version**: {version}"
]
